trigger:
  branches:
    include:
      - main

pool:
  name: servicios  # Usar el agente self-hosted en la VM

stages:
  - stage: Deploy
    jobs:
      - job: DeployToVM
        steps:
          - checkout: none
          - script: |
              echo "Trayendo los cambios..."
              cd /home/azureuser/pruebas/
              git pull

              echo "Construyendo imágenes Docker..."
              cd /home/azureuser/
              docker-compose down
              docker-compose build
              docker-compose up -d
            displayName: "Construir y ejecutar contenedores"
